### ISSUE TITLE
New timeline editor style tracker

### ISSUE THREAD

**Issue by coppolaemilio** [coppolaemilio/dialogic#704]
Making a list of all the things I know I have to finish before releasing this update:

- [x] New high resolution icons
	- [x] Text event
	- [x] Character Join
	- [x] Character Leave
	- [x] Question Event
	- [x] Choice event
	- [x] Close branch
	- [x] if event
	- [x] set value
	- [x] Set Glossary
	- [x] Label Event
	- [x] Go to Event
	- [x] Save
	- [x] Change Timeline
	- [x] Set Background
	- [x] Close Dialog
	- [x] Wait event
	- [x] Set theme
	- [x] Audio Event
	- [x] Background Music
	- [x] Emit Signal
	- [x] Change Scene
	- [x] Call Node
- [x] Add right click menu with the options that previously lived in the three dots menu
- [x] Question events base line not showing after the first indent level
- [x] If event indentation flow lines connections are broken
- [x] Better selection style
- [x] Text and Question text box never wraps for me, if you have long lines
- [x] Events body needs some indentation
	- [x] Audio Event
	- [x] Background Music
	- [x] Call Node
	- [x] Set Definition
	- [x] Audio Pickers on the Text Event
- [x] Add a "Help" option to the right-click-menu because the button got removed
- [x] Move the "Warning" Icon to somewhere else, because it looks pretty strange as it is

**Comment by Jowan-Spooner** [comment]
I've added a couple of points to the list, hope that's okay. 

I would also like to discuss some kind of standard look, placement and sizing of the contents of the events, so that the event parts could get cleaner and more intuitive as well. From what I can see, these are the most common things on events:

## Things on events
- [ ] _Resource Pickers (Character, Timeline, Definition, etc)_
Some have no Box around them right now
![grafik](https://user-images.githubusercontent.com/42868150/148844365-5a2bfe89-831f-4687-be31-d382ba76d9e8.png)
Some have:
![grafik](https://user-images.githubusercontent.com/42868150/148844528-81911b09-d007-4262-979e-62dcd5f68043.png)

- [ ] _Subresource Pickers (Portraits, Labels?)_ 
I would also imaging the Change Timeline event with a "Label" picker to start at a specific label
The Portrait Picker looks identical to the Character Picker which is probably okay, but it is not a resource per se, so maybe a difference could be good? not sure.
![grafik](https://user-images.githubusercontent.com/42868150/148844904-f9646d7f-5f76-42d5-b051-bf7d1a1e1cc2.png)


- [ ] _Text Input Fields (Choice Text, Signal Argument, Label Name)_
They mostly look like this:
![grafik](https://user-images.githubusercontent.com/42868150/148844928-7ee8d36c-74df-450c-adae-85efb89e8905.png)
For some things (like CHOICE and SET GLOSSARY) this one-line style could potentially be to small. It's extending to fit all content, but it never wraps and thus pushes all other options to the left and letting a horizontal scrollbar appear if you hava a long text in there.
![grafik](https://user-images.githubusercontent.com/42868150/148845158-884d6039-e179-4f1b-8785-a2cf30a6c8aa.png)
For the fields on `IF`, `SIGNAL` and `SET VALUE` this look is likely okay as you likely won't need long text there.
The CALL NODE has totally different very badly colored text fields.
![grafik](https://user-images.githubusercontent.com/42868150/148845631-ab8cbec2-05ef-4ec2-a801-54abd6fa539a.png)

- [ ] _Number Input Fields (Seconds, Set Value, etc.)_
These are the same pretty much everywhere, just the Godot Default. I think they are a bit hard to see on the default theme:
![grafik](https://user-images.githubusercontent.com/42868150/148847357-49b44de7-3094-4fa7-8c37-fcdeb187292a.png)

- [ ] _Option Picker (Position, Operation, Condition)_
These are probably the worst.
![grafik](https://user-images.githubusercontent.com/42868150/148847471-a9d74a3f-699f-4e8a-bea3-19003ca83da9.png)
![grafik](https://user-images.githubusercontent.com/42868150/148847677-333e4c38-12ab-4069-8e91-05b9172e38e8.png)
![grafik](https://user-images.githubusercontent.com/42868150/148847642-95671069-264d-4dc1-9abc-de641e5ddb08.png)

Not sure what's the best option for the Position picker, it's a bit special here. But this can't go on...


- [ ] _Boolean Pickers (Wait Event, Save Event, Choice, Set Value, Join) # with or_ 
Some have text, some not (Set Value>RANDOM or Character Join>MIRROR are just icons)

- [ ] _File pickers (Background Image)_

- [ ] _Audio Pickers_ 
they are just SUPER different. I know that I'm to blame, but maybe if we rework/rethink all of them, there is a good way to standardize them

- [ ] _Explanatory Labels_
These are handled/used quite inconsitently as well. Sometimes there is a Label that explains the function in a sentence. Sometimes there are lots of small labels that form a "Sentence". Sometimes there is "Additional Information"
![grafik](https://user-images.githubusercontent.com/42868150/148848035-0a83ff89-b2d8-4f37-9aee-24bc3860b028.png)
![grafik](https://user-images.githubusercontent.com/42868150/148848098-739ebaa7-b5c5-4393-a58b-4d523f962134.png)
![grafik](https://user-images.githubusercontent.com/42868150/148848018-e33a5a8f-a90f-4434-a153-0f00c860577e.png)
Maybe making it more clear what is a button and what is text would be good.


## Sizing, Stretching and Positioning
- [ ] There are still a couple of event parts that do not align in the center vertically. It's very annoying. I think everything should be centered in the middle (vertically). 
![grafik](https://user-images.githubusercontent.com/42868150/148845851-f48947b9-f2d6-49a7-8d1b-16cd155d60e5.png)
Other things that do that (I think): CHARACTER JOIN, WAIT SECONDS, CHANGE SCENE, SET VALUE

- [ ] Then there is the question if the things should expanding to fill out the availabale space vertically. I think it looks strange, so I'm against it. But some elements do it:
![grafik](https://user-images.githubusercontent.com/42868150/148846932-ddb8f268-045f-4433-bd8a-d5f20346da02.png)
![grafik](https://user-images.githubusercontent.com/42868150/148846960-c7d8c154-7361-4dc6-b186-64c67731aed6.png)
Happens on: SET THEME, SET GLOSSARY, SET BACKGROUND, maybe some others

- [ ] I also think it could be good to give things like the pickers default sizes, so that not everything moves all the time (when changing from a short to a long word). Sam goes for the Event Name (if needed at all). Right now all events content starts at a different point:
![grafik](https://user-images.githubusercontent.com/42868150/148847264-c8958062-432f-4863-a564-b671e4cb8dfe.png)
Maybe it would look cleaner if that wasn't the case.

## Header vs. Body
- [ ] And then there is the general question of "How much should be in the event header". Personally I think only the REALLY important settings. 
I think the timelines would look much cleaner if many settings would be moved into the body. Here are some suggestions: 
- WAIT SECONDS 'skippable' and 'Hide DialogBox' option
- SET VALUE 'random numbers' options
- CHOICE 'condition' options
- CHARACTER JOIN 'mirrored' option
- SET BACKGROUND 'fade-in duration' option
Of course for some of these it would mean a single setting in the body, which is the reason it wasn't done for many of them till now. But I think it would make the timeline much less crowded most of the time. 

Well that's all for now. Gonna complain about the event names somewhere else ;)

**Comment by Jowan-Spooner** [comment]
Some more things I noticed:
- [ ] Character Join has only 'Character' as it's name. Why?
- [ ] The `Save` Event has a very different color then it's button. One has to be changed
- [ ] The `Wait Seconds` Event has a very different color then it's button. One has to be changed.
- [ ] `Audio Event` and `Background Music` have different colors. Why? 
- [ ] `Change Scene`  Event has a very different color then it's button. One has to be changed
- [ ] All colors of the circles are more saturated then the buttons. Tha's okay, but could be changed.


Some things I thought of (but aren't really _wrong_):
- [ ] `Wait Seconds` could be renamed to `Wait`. I personally like shorter names, but oc both are okay.
- [ ] `Set Theme` and `Set Background` could be renamed to `Change Theme` and `Change Background` because set is used for values and definitions and to me means more a "behind the scenes change", while `Change Timeline` and `Change Scene` use the Change word.
- [ ] I feel like to many events have the purple color right now. It's hard to differentiate them. I would prefer 
    QUESTION, CHOICE, END BRANCH, CONDITION => Color A (could be purple)
    SET VALUE, SET DEFINITION => Color B
    GO TO, LABEL, CHANGE TIMELINE, CLOSE DIALOG => Color C
    SAVE => Color D
    WAIT => Color E
we could also rethink the colors of the other events, but they don't annoy me that much, only that I would
- [ ] Reorder the 'Timeline' events section so Set Theme and Set Background are together. Or maybe they should have their own section? Idk.

**Comment by coppolaemilio** [comment]
> Character Join has only 'Character' as it's name. Why?

I wanted to merge both character join and character leave events into one. So my idea was to do:
Character `[join/leave]` `[Character]` `[position]`

**Comment by coppolaemilio** [comment]
I'll go ahead now pick a proper color palette and clean those issues with the colors because I've been improvising a lot

**Comment by coppolaemilio** [comment]
I fixed the question lines bug. Unfortunately, since it is the same events who are in charge of drawing the lines themselves, once these go **outside the screen** you can't continue drawing the line which really sucks... The solution might be making the timeline editor being the one drawing the connection lines, but this might be a bit of work.


There isn't seems to be a workaround this issue: https://github.com/godotengine/godot/issues/17917

**Comment by Jowan-Spooner** [comment]
Hm this is quite annoying indeed, because it's very likely for conditions or questions to be too long to fit into the screen. I'll see if I can do something about it.

**Comment by coppolaemilio** [comment]
@Jowan-Spooner not sure if there is a way to force the draw function or if we have to maybe prevent those nodes from going outside of the window (like `if rect_global_position.y < 1: rect_global_position.y = 1`) or some random stuff like that. Otherwise like I said, it has to be drawn by a node that is always visible, ie: the timeline editor itself
