### ISSUE TITLE
[Tracker] Event refactoring

### ISSUE THREAD

**Issue by AnidemDex** [coppolaemilio/dialogic#869]
> To make things clear and organized ~~(and mainly to avoid making a giant PR)~~ I will make this issue to track this integration by pieces.
> This is part of https://github.com/coppolaemilio/dialogic/discussions/751
---
The goal is to replace current event format from JSON to Godot Resource and, in a different integration, to JSON (or whatever format you like) again. This was discussed previously in https://github.com/coppolaemilio/dialogic/issues/10

### Integration part
- [ ] **Add Event class.** This class serves as an abstract class for every event that can be executed in the timeline
- [ ] **Add Timeline class.** This class works as an event container, and the dialog node uses it to iterate over the events.
- [ ] **Rebuild events** with the new integration.
### Verification part
- [ ] Make sure that editor uses the new event class
- [ ] Make sure that editor uses the new timeline class
- [ ] Reorganize dialogic dialog node to use the timeline and event class.
### Cleanup part
- [ ] Remove scripts that may be deprecated by this integration. I'll need help verifying this one.

Event and Timeline class are based on [EventSystem](https://github.com/AnidemDex/Godot-EventSystem) scheme.

**Comment by Jowan-Spooner** [comment]
As far as I can tell this is basically done, even if the event class will probably see changes, Dialogic 2.0 now fully works with these resources.
